remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: "You're being targeted by disinformation networks that are vastly more effective than you realize"
description: "And they're making you more hateful and depressed."
